### ISSUE TITLE
Add missing LGBT MPs

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#2]
I note that on the section relating to LGBT MPs of various political parties there are a couple missing from your list including:

•	Lib Dem MP Sarah Dyke, who is openly gay on Twitter: https://twitter.com/SarahDykeLD?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

•	SNP MP Kirsty Blackman, who stated she wasn’t straight on twitter: https://twitter.com/KirstySNP/status/1668923027151618049

Thanks!

**Comment by johnpeart** [comment]
Thank you.

I've now updated the dataset to include Kirsty Blackman.

I haven't yet included Sarah Dyke. In general I have chosen only to include an MP in this dataset where it is clear that the individual has made an affirmative decision to reveal their identity publicly. These sources might include media reporting or personal testimony. I can't see a direct reference to being LGBT+ in Sarah's public comments. I do see an LGBT pride flag in her profile, but that could be a symbol of support rather than her being LGBT+. If you're able to point to a more specific reference, I'm happy to update the dataset to include them.

**Comment by HereAgain2024** [comment]
Dear John,

I was just reading an article from Pink News:
https://www.thepinknews.com/2024/07/03/lgbtq-representation-house-of-commons-general-election/
and
it has now included Sarah Dyke in the article as an out LGBT+ MP, so I was
wondering if you might be able to add them to your LGBT database:
https://mps.whoare.lgbt/

Also Kieran Mullin, the Conservative MP, has been re-elected:
https://www.bbc.co.uk/news/election/2024/uk/constituencies/E14001088, also
Blake Stephenson, who is openly gay, has been elected to Mid Bedforshire:
https://www.biggleswadetoday.co.uk/news/politics/mid-bedfordshire-2024-general-election-results-4691733

Kind regards,

Dr Michael Taylor

**Comment by HereAgain2024** [comment]
Dear John,

Pink News updated the amount of LGBT MPs and it now includes Tom Gordon,
the Lib Dem MP for Harrogate and Knarsborough:
https://www.thepinknews.com/2024/07/05/lgbtq-mps-general-election/.

Kind regards,

Michael
